### ISSUE TITLE
Secret key is not meant to be used in a bundled app

### ISSUE THREAD

**Issue by ibrahimlawal** [KingIdee/paystack-android-sample#1]
@KingIdee Awesome work here. Would not encourage that anyone follows this for a live app though.  Your secret key should only be used on the server where only your trusted engineers have access to it.

**Comment by KingIdee** [comment]
Thanks! But why is a personal server for live hosting highly recommended?

**Comment by ibrahimlawal** [comment]
@KingIdee if you include your secret key in a mobile it, that app can be unbundled and the key used against you.

Again, for your safety, your own server should be in charge of all communications with us so you know your secret key is safe.

**Comment by KingIdee** [comment]
Ok. Noted with thanks
